# Generated by Django 5.1.4 on 2025-02-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nature',
            name='image',
            field=models.ImageField(upload_to='nature/'),
        ),
    ]
