# Generated by Django 5.1.4 on 2025-02-27 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharma', '0002_alter_nature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('xp_cost', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('requirements', models.CharField(max_length=100)),
                ('effect', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='technique/')),
            ],
        ),
        migrations.AlterField(
            model_name='nature',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nature/'),
        ),
    ]
