# Generated by Django 5.1.4 on 2025-02-28 00:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharma', '0003_technique_alter_nature_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('damage', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='weapon/')),
            ],
        ),
    ]
