version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dungeon_hub_db
    restart: always
    environment:
      POSTGRES_DB: dungeon_hub
      POSTGRES_USER: dungeon_user
      POSTGRES_PASSWORD: dungeon@123
    ports:
      - "5432:5432"
